# version field removed as it is obsolete
services:
  backend:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:QC%402025@host.docker.internal:5432/Inventory_mang
      - API_SECRET_KEY=dev-secret-key
    volumes:
      - ./backend:/src
    ports:
      - "8000:8000"
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./frontend_full
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend