# version field removed as it is obsolete
services:
  backend:
    build: ./backend/app
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgresql://postgres:QC%402025@host.docker.internal:5432/Inventory_mang
      - API_SECRET_KEY=your-super-secret-key-change-this-in-production
      - PYTHONPATH=/
    volumes:
      - ./backend/app:/app
    ports:
      - "3002:3002"
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 3002 --reload"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=http://backend:3002
    ports:
      - "3001:80"
    depends_on:
      - backend
