"""Drop global unique on sku, add per-owner unique

Revision ID: 001
Revises: 
Create Date: 2024-10-01 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_sku', table_name='products')
    op.create_index(op.f('ix_products_sku_owner_id'), 'products', ['sku', 'owner_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_sku_owner_id'), table_name='products')
    op.create_index('ix_products_sku', 'products', ['sku'], unique=True)
    # ### end Alembic commands ###
