"""add rejection_reason to stock_movement_requests

Revision ID: ae0c47180d53
Revises: ff21cd34e513
Create Date: 2025-10-03 12:10:54.882747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae0c47180d53'
down_revision: Union[str, Sequence[str], None] = 'ff21cd34e513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_movement_requests', sa.Column('rejection_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_movement_requests', 'rejection_reason')
    # ### end Alembic commands ###
